### ISSUE TITLE
TypeError when using timeout with node-fetch polyfill

### ISSUE THREAD

**Issue by xpuu** [elbywan/wretch#86]
This code (running in node v14.4.0)
```javascript
import fetch from 'node-fetch'
import wretch from 'wretch'

wretch('http://foobar.baz').polyfills({ fetch }).get().setTimeout(1)
```
results with
```
TypeError: Cannot read property 'abort' of undefined
    at Timeout._onTimeout (/wretch/node-fetch/node_modules/wretch/dist/bundle/wretch.js:1:6101)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```
Any idea what's wrong? Thanks in advance.

**Comment by elbywan** [comment]
Hi @xpuu,

`node-fetch` needs an `AbortController` polyfill to support that feature. (as written in the [documentation](https://github.com/elbywan/wretch#abortable-requests))

```js
const fetch = require('node-fetch')
const AbortController = require('abort-controller')
const wretch = require('wretch')

wretch('https://duckduckgo.com')
    .polyfills({ fetch, AbortController })
    .get()
    .setTimeout(1)
    .text(console.log)
// -> AbortError: The user aborted a request.
```

More info [here](https://github.com/node-fetch/node-fetch#request-cancellation-with-abortsignal).

**Comment by xpuu** [comment]
Wow, that was quick! Once again thanks for your support.
